/*
 * Copyright (c) 2025 Oracle and/or its affiliates.
 *
 * Licensed under the Universal Permissive License v 1.0 as shown at
 * https://oss.oracle.com/licenses/upl.
 *
 */
package com.oracle.weblogic.rewrite.jakarta;

import org.junit.jupiter.api.Test;
import org.openrewrite.test.RewriteTest;

import static org.openrewrite.maven.Assertions.pomXml;

public class UpgradePluginConfigurationArtifactItemsTest implements RewriteTest  {

    @Test
    void changePluginArtifactItemGroupArtifact() {
        rewriteRun(spec -> spec.recipe(new UpgradePluginConfigurationArtifactItems("javax", "javaee-api",
            "jakarta.platform", "jakarta.jakartaee-api", null)),
          //language=xml
          pomXml(
            """
              <project>
                  <modelVersion>4.0.0</modelVersion>
                  <groupId>com.mycompany.app</groupId>
                  <artifactId>my-app</artifactId>
                  <version>1</version>
                  <properties>
                      <jakartaee>8.0</jakartaee>
                  </properties>
                  <build>
                      <plugins>
                         <plugin>
                             <groupId>org.apache.maven.plugins</groupId>
                             <artifactId>maven-dependency-plugin</artifactId>
                             <version>2.6</version>
                             <executions>
                                 <execution>
                                     <phase>validate</phase>
                                     <goals>
                                         <goal>copy</goal>
                                     </goals>
                                     <configuration>
                                         <outputDirectory>${endorsed.dir}</outputDirectory>
                                         <silent>true</silent>
                                         <artifactItems>
                                              <artifactItem>
                                                   <groupId>javax</groupId>
                                                   <artifactId>javaee-api</artifactId>
                                                   <version>${jakartaee}</version>
                                                   <type>jar</type>
                                              </artifactItem>
                                              <artifactItem>
                                                   <groupId>junit</groupId>
                                                   <artifactId>junit</artifactId>
                                                   <version>3.8.1</version>
                                                   <scope>test</scope>
                                              </artifactItem>
                                         </artifactItems>
                                     </configuration>
                                 </execution>
                             </executions>
                         </plugin>
                      </plugins>
                  </build>
              </project>
              """,
            """
              <project>
                  <modelVersion>4.0.0</modelVersion>
                  <groupId>com.mycompany.app</groupId>
                  <artifactId>my-app</artifactId>
                  <version>1</version>
                  <properties>
                      <jakartaee>8.0</jakartaee>
                  </properties>
                  <build>
                      <plugins>
                         <plugin>
                             <groupId>org.apache.maven.plugins</groupId>
                             <artifactId>maven-dependency-plugin</artifactId>
                             <version>2.6</version>
                             <executions>
                                 <execution>
                                     <phase>validate</phase>
                                     <goals>
                                         <goal>copy</goal>
                                     </goals>
                                     <configuration>
                                         <outputDirectory>${endorsed.dir}</outputDirectory>
                                         <silent>true</silent>
                                         <artifactItems>
                                              <artifactItem>
                                                   <groupId>jakarta.platform</groupId>
                                                   <artifactId>jakarta.jakartaee-api</artifactId>
                                                   <version>${jakartaee}</version>
                                                   <type>jar</type>
                                              </artifactItem>
                                              <artifactItem>
                                                   <groupId>junit</groupId>
                                                   <artifactId>junit</artifactId>
                                                   <version>3.8.1</version>
                                                   <scope>test</scope>
                                              </artifactItem>
                                         </artifactItems>
                                     </configuration>
                                 </execution>
                             </executions>
                         </plugin>
                      </plugins>
                  </build>
              </project>
              """
          )
        );
    }

    @Test
    void changePluginArtifactItemGroupArtifactInProperties() {
        rewriteRun(spec -> spec.recipe(new UpgradePluginConfigurationArtifactItems("javax", "javaee-api",
            "jakarta.platform", "jakarta.jakartaee-api", null)),
          //language=xml
          pomXml(
            """
              <project>
                  <modelVersion>4.0.0</modelVersion>
                  <groupId>com.mycompany.app</groupId>
                  <artifactId>my-app</artifactId>
                  <version>1</version>
                  <properties>
                      <jakartaee>8.0</jakartaee>
                      <test.javax.prop>javax</test.javax.prop>
                      <test.javaee.api.prop>javaee-api</test.javaee.api.prop>
                  </properties>
                  <build>
                      <plugins>
                         <plugin>
                             <groupId>org.apache.maven.plugins</groupId>
                             <artifactId>maven-dependency-plugin</artifactId>
                             <version>2.6</version>
                             <executions>
                                 <execution>
                                     <phase>validate</phase>
                                     <goals>
                                         <goal>copy</goal>
                                     </goals>
                                     <configuration>
                                         <outputDirectory>${endorsed.dir}</outputDirectory>
                                         <silent>true</silent>
                                         <artifactItems>
                                              <artifactItem>
                                                   <groupId>${test.javax.prop}</groupId>
                                                   <artifactId>${test.javaee.api.prop}</artifactId>
                                                   <version>${jakartaee}</version>
                                                   <type>jar</type>
                                              </artifactItem>
                                              <artifactItem>
                                                   <groupId>junit</groupId>
                                                   <artifactId>junit</artifactId>
                                                   <version>3.8.1</version>
                                                   <scope>test</scope>
                                              </artifactItem>
                                         </artifactItems>
                                     </configuration>
                                 </execution>
                             </executions>
                         </plugin>
                      </plugins>
                  </build>
              </project>
              """,
            """
              <project>
                  <modelVersion>4.0.0</modelVersion>
                  <groupId>com.mycompany.app</groupId>
                  <artifactId>my-app</artifactId>
                  <version>1</version>
                  <properties>
                      <jakartaee>8.0</jakartaee>
                      <test.javax.prop>jakarta.platform</test.javax.prop>
                      <test.javaee.api.prop>jakarta.jakartaee-api</test.javaee.api.prop>
                  </properties>
                  <build>
                      <plugins>
                         <plugin>
                             <groupId>org.apache.maven.plugins</groupId>
                             <artifactId>maven-dependency-plugin</artifactId>
                             <version>2.6</version>
                             <executions>
                                 <execution>
                                     <phase>validate</phase>
                                     <goals>
                                         <goal>copy</goal>
                                     </goals>
                                     <configuration>
                                         <outputDirectory>${endorsed.dir}</outputDirectory>
                                         <silent>true</silent>
                                         <artifactItems>
                                              <artifactItem>
                                                   <groupId>${test.javax.prop}</groupId>
                                                   <artifactId>${test.javaee.api.prop}</artifactId>
                                                   <version>${jakartaee}</version>
                                                   <type>jar</type>
                                              </artifactItem>
                                              <artifactItem>
                                                   <groupId>junit</groupId>
                                                   <artifactId>junit</artifactId>
                                                   <version>3.8.1</version>
                                                   <scope>test</scope>
                                              </artifactItem>
                                         </artifactItems>
                                     </configuration>
                                 </execution>
                             </executions>
                         </plugin>
                      </plugins>
                  </build>
              </project>
              """
          )
        );
    }

    @Test
    void validateRecipeDoesntAlterOtherDependencies() {
        rewriteRun(spec -> spec.recipe(new UpgradePluginConfigurationArtifactItems("javax", "javaee-api",
            "jakarta.platform", "jakarta.jakartaee-api", null)),
          //language=xml
          pomXml(
            """
              <project>
                  <modelVersion>4.0.0</modelVersion>
                  <groupId>com.mycompany.app</groupId>
                  <artifactId>my-app</artifactId>
                  <version>1</version>
                  <properties>
                      <jakartaee>8.0</jakartaee>
                      <test.javax.prop>javax</test.javax.prop>
                      <test.javaee.api.prop>javaee-api</test.javaee.api.prop>
                  </properties>
                  <dependencies>
                      <dependency>
                        <groupId>javax</groupId>
                        <artifactId>javaee-api</artifactId>
                        <version>${jakartaee}</version>
                        <scope>provided</scope>
                      </dependency>
                  </dependencies>
                  <build>
                      <plugins>
                         <plugin>
                             <groupId>org.apache.maven.plugins</groupId>
                             <artifactId>maven-dependency-plugin</artifactId>
                             <version>2.6</version>
                             <executions>
                                 <execution>
                                     <phase>validate</phase>
                                     <goals>
                                         <goal>copy</goal>
                                     </goals>
                                     <configuration>
                                         <outputDirectory>${endorsed.dir}</outputDirectory>
                                         <silent>true</silent>
                                         <artifactItems>
                                              <artifactItem>
                                                   <groupId>javax</groupId>
                                                   <artifactId>javaee-api</artifactId>
                                                   <version>${jakartaee}</version>
                                                   <type>jar</type>
                                              </artifactItem>
                                              <artifactItem>
                                                   <groupId>junit</groupId>
                                                   <artifactId>junit</artifactId>
                                                   <version>3.8.1</version>
                                                   <scope>test</scope>
                                              </artifactItem>
                                         </artifactItems>
                                     </configuration>
                                 </execution>
                             </executions>
                         </plugin>
                      </plugins>
                  </build>
              </project>
              """,
            """
              <project>
                  <modelVersion>4.0.0</modelVersion>
                  <groupId>com.mycompany.app</groupId>
                  <artifactId>my-app</artifactId>
                  <version>1</version>
                  <properties>
                      <jakartaee>8.0</jakartaee>
                      <test.javax.prop>javax</test.javax.prop>
                      <test.javaee.api.prop>javaee-api</test.javaee.api.prop>
                  </properties>
                  <dependencies>
                      <dependency>
                        <groupId>javax</groupId>
                        <artifactId>javaee-api</artifactId>
                        <version>${jakartaee}</version>
                        <scope>provided</scope>
                      </dependency>
                  </dependencies>
                  <build>
                      <plugins>
                         <plugin>
                             <groupId>org.apache.maven.plugins</groupId>
                             <artifactId>maven-dependency-plugin</artifactId>
                             <version>2.6</version>
                             <executions>
                                 <execution>
                                     <phase>validate</phase>
                                     <goals>
                                         <goal>copy</goal>
                                     </goals>
                                     <configuration>
                                         <outputDirectory>${endorsed.dir}</outputDirectory>
                                         <silent>true</silent>
                                         <artifactItems>
                                              <artifactItem>
                                                   <groupId>jakarta.platform</groupId>
                                                   <artifactId>jakarta.jakartaee-api</artifactId>
                                                   <version>${jakartaee}</version>
                                                   <type>jar</type>
                                              </artifactItem>
                                              <artifactItem>
                                                   <groupId>junit</groupId>
                                                   <artifactId>junit</artifactId>
                                                   <version>3.8.1</version>
                                                   <scope>test</scope>
                                              </artifactItem>
                                         </artifactItems>
                                     </configuration>
                                 </execution>
                             </executions>
                         </plugin>
                      </plugins>
                  </build>
              </project>
              """
          )
        );
    }

    @Test
    void validateRecipeDoesntAlterNonExistingArtifact() {
        rewriteRun(spec -> spec.recipe(new UpgradePluginConfigurationArtifactItems("javax", "javaee-api",
            "jakarta.platform", "jakarta.jakartaee-api", null)),
          //language=xml
          pomXml(
            """
              <project>
                  <modelVersion>4.0.0</modelVersion>
                  <groupId>com.mycompany.app</groupId>
                  <artifactId>my-app</artifactId>
                  <version>1</version>
                  <properties>
                      <jakartaee>8.0</jakartaee>
                      <test.javax.prop>javax</test.javax.prop>
                      <test.javaee.api.prop>javaee-api</test.javaee.api.prop>
                  </properties>
                  <dependencies>
                      <dependency>
                        <groupId>javax</groupId>
                        <artifactId>javaee-api</artifactId>
                        <version>${jakartaee}</version>
                        <scope>provided</scope>
                      </dependency>
                  </dependencies>
                  <build>
                      <plugins>
                         <plugin>
                             <groupId>org.apache.maven.plugins</groupId>
                             <artifactId>maven-dependency-plugin</artifactId>
                             <version>2.6</version>
                             <executions>
                                 <execution>
                                     <phase>validate</phase>
                                     <goals>
                                         <goal>copy</goal>
                                     </goals>
                                     <configuration>
                                         <outputDirectory>${endorsed.dir}</outputDirectory>
                                         <silent>true</silent>
                                         <artifactItems>
                                              <artifactItem>
                                                   <groupId>junit</groupId>
                                                   <artifactId>junit</artifactId>
                                                   <version>3.8.1</version>
                                                   <scope>test</scope>
                                              </artifactItem>
                                         </artifactItems>
                                     </configuration>
                                 </execution>
                             </executions>
                         </plugin>
                      </plugins>
                  </build>
              </project>
              """
          )
        );
    }
}
